//! M2 gate test — the explicit, named exit gate for milestone M2.
//!
//! Per the v2 PLAN: "a clean checkout of *only* the verifier crate
//! verifies a bundle exported by M1. (If it needs internal crates,
//! the format is wrong.)"
//!
//! This file runs in `cloakpipe-verify` itself (so it has access to
//! the verifier API), but it does NOT import `cloakpipe-ledger`. The
//! bundle is loaded from a JSON file on disk — exactly as the CLI
//! does. If the verifier's API ever sneaks a dependency on the
//! producer crate, this test will still pass; the CLI gate is a
//! separate, harder check (a process-level invocation).
//!
//! The companion end-to-end CLI gate lives in `m2_e2e.rs` and uses
//! `std::process::Command` to invoke the built binary.

#![cfg(test)]

use cloakpipe_verify::bundle::{Bundle, BUNDLE_FORMAT_VERSION, BUNDLE_MAGIC};
use cloakpipe_verify::verify::{check_magic, verify_all, verify_chain, verify_sigs};
use std::path::PathBuf;

fn fixture_path() -> PathBuf {
    // The fixture bundle is generated by the producer at build time
    // — see `tests/build_fixture.rs`. We just consume it here.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/sample.bundle.json")
}

#[test]
fn fixture_bundle_passes_every_check() {
    let raw = std::fs::read_to_string(fixture_path()).expect("fixture exists");
    let bundle: Bundle = serde_json::from_str(&raw).expect("valid JSON");
    check_magic(&bundle).expect("magic");
    let tip = verify_chain(&bundle).expect("chain");
    let n = verify_sigs(&bundle).expect("sigs");
    let summary = verify_all(&bundle).expect("all");
    assert_eq!(summary.chain_tip, tip);
    assert_eq!(summary.signatures, n);
    assert_eq!(summary.records, bundle.records.len());
}

#[test]
fn bundle_format_magic_and_version() {
    let raw = std::fs::read_to_string(fixture_path()).unwrap();
    let bundle: Bundle = serde_json::from_str(&raw).unwrap();
    assert_eq!(bundle.format, BUNDLE_MAGIC);
    assert_eq!(bundle.format_version, BUNDLE_FORMAT_VERSION);
}

#[test]
fn v1_bundle_is_accepted_for_backward_compat() {
    // Bundles shipped before M3 had format_version=1. They lack
    // inclusion proofs and anchor receipts; the verifier must
    // accept them, just skip the M3-only checks.
    let raw = std::fs::read_to_string(fixture_path()).unwrap();
    let mut bundle: Bundle = serde_json::from_str(&raw).unwrap();
    bundle.format_version = 1;
    bundle.inclusion_proofs.clear();
    bundle.anchor_receipts.clear();
    let tip = verify_chain(&bundle).expect("v1 chain verifies");
    assert!(!tip.is_empty());
}

#[test]
fn tamper_canonical_bytes_fails_chain() {
    let raw = std::fs::read_to_string(fixture_path()).unwrap();
    let mut bundle: Bundle = serde_json::from_str(&raw).unwrap();
    if bundle.records.is_empty() {
        panic!("fixture has no records");
    }
    // Flip one byte in the canonical bytes of record 0.
    let mut bytes = bundle.records[0].canonical_bytes.clone();
    if bytes.is_empty() {
        panic!("empty canonical bytes");
    }
    let first = bytes.remove(0);
    bytes.insert(0, if first == 'A' { 'B' } else { 'A' });
    bundle.records[0].canonical_bytes = bytes;
    assert!(verify_chain(&bundle).is_err());
}